/// Auto-generated by Xcode Build Phase. Do not edit.
enum BuildInfo {
    static let gitCommitHash = "8a56311"
    static let gitCommitHashFull = "8a563110a90fd27d1641a3c25cc4232469b7dbcb"
    static let version = "0.0.0"
}
