/// Auto-generated by Xcode Build Phase. Do not edit.
enum BuildInfo {
    static let gitCommitHash = "84d9312"
    static let gitCommitHashFull = "84d9312603fa7c046d75aa1fb4b07e5a9d52ae16"
    static let version = "0.0.0"
}
